global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@zamaz-debate.local'
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    repeat_interval: 30m
  - match:
      severity: warning
    receiver: 'warning-alerts'
    repeat_interval: 2h
  - match:
      severity: info
    receiver: 'info-alerts'
    repeat_interval: 24h

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhooks/alerts'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'alertmanager'
        password: 'changeme'

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhooks/alerts/critical'
    send_resolved: true
    title: '[CRITICAL] Zamaz Debate System Alert'
    text: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      {{ end }}

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhooks/alerts/warning'
    send_resolved: true
    title: '[WARNING] Zamaz Debate System Alert'

- name: 'info-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhooks/alerts/info'
    send_resolved: true
    title: '[INFO] Zamaz Debate System Alert'

# Inhibit rules to prevent alert spam
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']
- source_match:
    severity: 'warning'
  target_match:
    severity: 'info'
  equal: ['alertname', 'instance']