name: Bot Gemini Listener

on:
  issue_comment:
    types: [created]

jobs:
  respond:
    if: github.event.comment.body contains '@bot_gemini'
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "Bot Gemini triggered by @${{ github.actor }} on issue #${{ github.event.issue.number }}"
